version: "3.8"

services:
  nginx:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - api
    networks:
      appnet:
        ipv4_address: 192.175.0.2
    restart: always
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/dbdata:/var/lib/postgresql/data
    networks:
      appnet:
        ipv4_address: 192.175.0.3
    ports:
      - 6500:5432
    restart: always
  api:
    image: peterihimire/book-app-challenge
    platform: linux/amd64
    build:
      context: .
      target: production
    depends_on:
      - db
    networks:
      appnet:
        ipv4_address: 192.175.0.4
    environment:
      - DB_HOST=db
      - PORT=${PORT}
      - JWT_KEY=${JWT_KEY}
    ports:
      - ${PORT}:${PORT} # Publish to host
    # expose:
    #   - "4040"
    restart: always

networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: "192.175.0.0/24"
          gateway: 192.175.0.1
