version: "3.8"

services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./data/pgdata:/var/lib/postgresql/data
    networks:
      appnet:
        ipv4_address: 192.168.0.3
    ports:
      - 5439:5432
    restart: always

  api:
    image: peterihimire/ecommerce-bkend-ts
    platform: linux/amd64
    build:
      context: .
      target: production
    depends_on:
      - db
      - redis
      - pgadmin
    networks:
      appnet:
        ipv4_address: 192.168.0.5
    environment:
      - DB_HOST=db
      - REDIS_HOST=redis
      - PORT=${PORT_ONE}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - REDIS_PORT=${REDIS_PORT}
      - SESSION_SECRET=${SESSION_SECRET}
      - ADMIN_SESSION_SECRET=${ADMIN_SESSION_SECRET}
      - CART_SESSION_SECRET=${CART_SESSION_SECRET}
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - PAYSTACK_PUBLIC_KEY=${PAYSTACK_PUBLIC_KEY}
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - STRIPE_PUBLISH_KEY=${STRIPE_PUBLISH_KEY}
      - STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY}
      - STRIPE_ENDPOINT_SECRET=${STRIPE_ENDPOINT_SECRET}
      - BREVO_API_KEY=${BREVO_API_KEY}
      - SMS_KEY=${SMS_KEY}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
    volumes:
      - ./documents/pdf:/app/documents/pdf # Mapping the static folder for PDFs
      - ./documents/image:/app/documents/image # Mapping the folder for images
      - ./documents/picture:/app/documents/picture # Mapping the folder for pictures
    ports:
      - ${PORT_ONE}:${PORT_ONE} # Publish to host
    # expose:
    #   - "4040"
    restart: always

networks:
  appnet:
    driver: bridge
    ipam:
      config:
        - subnet: "192.168.0.0/24"
          gateway: 192.168.0.1
